import React, { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import Navbar from '../components/landing/Navbar';
import Footer from '../components/landing/Footer';

const TermsOfService = () => {
  const location = useLocation();

  useEffect(() => {
    // Scroll to terms-of-service-section if hash is present in URL
    if (location.hash === '#terms-of-service-section') {
      setTimeout(() => {
        const element = document.getElementById('terms-of-service-section');
        if (element) {
          const offset = 100; // Account for navbar height
          const elementPosition = element.getBoundingClientRect().top;
          const offsetPosition = elementPosition + window.pageYOffset - offset;
          
          window.scrollTo({
            top: offsetPosition,
            behavior: 'smooth'
          });
        }
      }, 100);
    }
  }, [location.hash]);

  return (
    <div className="min-h-screen pt-28" style={{ backgroundColor: '#F9FAFC' }}>
      <Navbar />
      <div id="terms-of-service-section" className="w-full max-w-7xl mx-auto px-4 py-8 border-2 border-gray-200 shadow-lg" style={{ scrollMarginTop: '100px' }}>
        <h1 className="text-2xl font-bold mb-4" style={{ color: '#1E65AD', fontFamily: "'Bricolage Grotesque', sans-serif" }}>
          Terms of Service
        </h1>
        <p className="mb-6" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif" }}>
          Last updated: {new Date().toLocaleDateString('en-IN')}
        </p>

        {/* Introduction */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>1. Introduction</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            These Terms of Service ("Terms") constitute a legally binding agreement between
            ExpertSetu LLP, a limited liability partnership registered under the Limited Liability
            Partnership Act, 2008 (hereinafter referred to as "ExpertSetu", "the Company", "we",
            "our", or "us") and any natural or legal person ("User", "you", or "your") who accesses,
            registers for, or uses our website, platform, mobile applications, and all related
            software, features, and services offered by ExpertSetu (collectively, the "Services").
          </p>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            By accessing or using the Services, you agree to comply with and be bound by these
            Terms, our Privacy Policy, Cookie Policy, and Refund Policy (collectively, "Agreements").
            If you do not agree to any of these, you must not access or use our Services.
          </p>
        </section>

        {/* Eligibility */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>2. Eligibility</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            You represent that you are at least 18 years of age and capable of entering into a legally
            binding contract as per the Indian Contract Act, 1872. If you are using the Services on
            behalf of a business or legal entity, you represent that you have the authority to bind that
            entity to these Terms.
          </p>
        </section>

        {/* Scope of Services */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>3. Scope of Services</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            ExpertSetu operates an AI-powered legal assistance platform that provides users with
            automated research support, legal documentation assistance, and knowledge insights.
            The Services are intended to assist users in understanding legal topics but do not
            constitute legal advice.
          </p>
          <p className="mb-2" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>You acknowledge and agree that:</p>
          <ul className="list-disc pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>Outputs generated by the AI system are for informational purposes only.</li>
            <li>ExpertSetu is not a law firm and does not provide legal representation.</li>
            <li>You are solely responsible for verifying the accuracy, reliability, and applicability of any content generated by the platform.</li>
          </ul>
        </section>

        {/* Account Registration */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>4. Account Registration and Access</h2>
          <ol className="list-decimal pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>To access certain features, users may be required to create an account by providing accurate and complete information.</li>
            <li>You agree to maintain the confidentiality of your account credentials and are solely responsible for all activities occurring under your account.</li>
            <li>ExpertSetu reserves the right to suspend, disable, or terminate accounts suspected of unauthorized access, misuse, or violation of these Terms.</li>
          </ol>
        </section>

        {/* Acceptable Use Policy */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>5. Acceptable Use Policy</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>Users agree not to:</p>
          <ul className="list-disc pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>Use the Services for any unlawful, fraudulent, or malicious purpose.</li>
            <li>Upload or transmit any harmful, defamatory, or infringing content.</li>
            <li>Attempt to reverse-engineer, decompile, or copy the platform's software or AI algorithms.</li>
            <li>Interfere with system integrity or security.</li>
            <li>Use automated systems (bots, scrapers) without prior written consent.</li>
          </ul>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            Violation of this clause may lead to immediate termination and potential legal action.
          </p>
        </section>

        {/* Intellectual Property */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>6. Intellectual Property Rights</h2>
          <ol className="list-decimal pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>All intellectual property rights, including but not limited to source code, algorithms, text, graphics, designs, interfaces, and trademarks, are the sole property of ExpertSetu LLP.</li>
            <li>Nothing in these Terms shall grant you ownership or rights other than the limited license to use the Services for lawful purposes.</li>
            <li>Users may not copy, modify, distribute, or create derivative works based on any part of the platform without prior written consent.</li>
          </ol>
        </section>

        {/* Subscriptions and Payments */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>7. Subscriptions, Payments, and Billing</h2>
          <ol className="list-decimal pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>Certain Services are available through paid subscriptions. Payment details will be clearly communicated before purchase.</li>
            <li>All payments shall be processed securely through authorized payment gateways in compliance with the Reserve Bank of India (RBI) regulations.</li>
            <li>By subscribing, you authorize ExpertSetu to charge the applicable fees to your designated payment method.</li>
            <li>All fees are non-refundable, except as expressly provided in our Refund Policy.</li>
            <li>ExpertSetu reserves the right to modify pricing or subscription terms with prior notice via email or website announcement.</li>
          </ol>
        </section>

        {/* Data Protection */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>8. Data Protection and Privacy</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            ExpertSetu collects and processes user data in accordance with the Digital Personal
            Data Protection Act, 2023, the Information Technology Act, 2000, and its allied rules.
            Our detailed data-handling practices are provided in the Privacy Policy, which forms an
            integral part of these Terms.
          </p>
        </section>

        {/* Disclaimers */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>9. Disclaimers</h2>
          <ol className="list-decimal pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>The Services and all outputs provided by the AI system are on an "as is" and "as available" basis without warranties of any kind.</li>
            <li>ExpertSetu does not guarantee that the information generated will be accurate, up-to-date, or applicable to a particular legal situation.</li>
            <li>No content provided through the Services constitutes professional legal advice. Users should consult a qualified advocate for legal matters.</li>
          </ol>
        </section>

        {/* Limitation of Liability */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>10. Limitation of Liability</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>To the maximum extent permitted by applicable law:</p>
          <ul className="list-disc pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>ExpertSetu LLP shall not be liable for any indirect, consequential, incidental, or punitive damages arising from or in connection with the use of the Services.</li>
            <li>Our total liability in any event shall not exceed the total subscription amount paid by the user in the preceding three (3) months.</li>
            <li>ExpertSetu shall not be responsible for loss of data, profits, or goodwill resulting from any malfunction, delay, or interruption of the platform.</li>
          </ul>
        </section>

        {/* Indemnification */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>11. Indemnification</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            You agree to indemnify and hold harmless ExpertSetu LLP, its partners, employees,
            and affiliates against all claims, damages, liabilities, and expenses (including legal fees)
            arising from your breach of these Terms, misuse of the Services, or violation of any law
            or third-party rights.
          </p>
        </section>

        {/* Termination */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>12. Termination</h2>
          <ol className="list-decimal pl-6 mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <li>ExpertSetu reserves the right to terminate or suspend your account and access to the Services at any time for breach of these Terms or misuse of the platform.</li>
            <li>Upon termination, all rights granted to you under these Terms shall immediately cease.</li>
          </ol>
        </section>

        {/* Governing Law */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>13. Governing Law and Jurisdiction</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            These Terms shall be governed by and construed in accordance with the laws of India.
            All disputes arising hereunder shall be subject to the exclusive jurisdiction of the courts
            located in Ahmedabad, Gujarat.
          </p>
        </section>

        {/* Amendments */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>14. Amendments</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            ExpertSetu may revise these Terms periodically. Any material changes will be notified
            via email or a notice on our website. Continued use of the Services constitutes
            acceptance of the revised Terms.
          </p>
        </section>

        {/* Contact Information */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3" style={{ color: '#1E65AD', fontFamily: "'Heebo', sans-serif" }}>15. Contact Information</h2>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            For questions or concerns regarding these Terms, please contact:
          </p>
          <p className="mb-2" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <strong>ExpertSetu LLP</strong><br />
            Legal Department
          </p>
          <p className="mb-2" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <strong>Email:</strong>{' '}
            <a href="mailto:inquiry@salhakar.com" style={{ color: '#1E65AD', textDecoration: 'underline' }}>
              inquiry@salhakar.com
            </a>
          </p>
          <p className="mb-4" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif", lineHeight: '1.6' }}>
            <strong>Response Time:</strong> Within 48 hours
          </p>
        </section>

        <div className="mt-12 pt-8 text-center">
          <p className="text-sm" style={{ color: '#8C969F', fontFamily: "'Heebo', sans-serif" }}>
            These Terms of Service are effective as of the date of last update and apply to all users of our Services.
          </p>
        </div>
      </div>
      
    </div>
  );
};

export default TermsOfService;
